print("hello how are you")
print("Honesty is the best policy")
print("HELLOOOOOO")
print("Honesty is the best policy")
print("helooo")
print("Tuesday  for conflict")
print("Sunday is not good weather")
